import type { ThemePreset } from "./types";

export const calNeutralTheme: ThemePreset = {
  name: "cal-neutral",
  description: "Cal.com-inspired neutral light theme.",
  colors: {
    background: "#ffffff",
    foreground: "#111111",
    card: "#ffffff",
    cardForeground: "#111111",
    popover: "#ffffff",
    popoverForeground: "#111111",
    primary: "#111111",
    primaryForeground: "#ffffff",
    secondary: "#f5f5f5",
    secondaryForeground: "#111111",
    muted: "#f5f5f5",
    mutedForeground: "#666666",
    accent: "#111111",
    accentForeground: "#ffffff",
    destructive: "#dc2626",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#e5e5e5",
    ring: "#111111",
  },
  spacing: {
    1: "4px",
    2: "8px",
    3: "12px",
    4: "16px",
    6: "24px",
    8: "32px",
    12: "48px",
    16: "64px",
    24: "96px",
  },
  radius: {
    sm: "8px",
    md: "12px",
    lg: "16px",
    xl: "24px",
    full: "9999px",
  },
  typography: {
    sans: "Inter, ui-sans-serif, system-ui, sans-serif",
    mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace',
    heading: "Inter, ui-sans-serif, system-ui, sans-serif",
    baseSize: "16px",
  },
};

export const calInkTheme: ThemePreset = {
  name: "cal-ink",
  description: "High-contrast dark variant for focused work surfaces.",
  colors: {
    background: "#0b0b0b",
    foreground: "#f5f5f5",
    card: "#111111",
    cardForeground: "#f5f5f5",
    popover: "#111111",
    popoverForeground: "#f5f5f5",
    primary: "#f5f5f5",
    primaryForeground: "#0b0b0b",
    secondary: "#1a1a1a",
    secondaryForeground: "#f5f5f5",
    muted: "#1a1a1a",
    mutedForeground: "#a3a3a3",
    accent: "#f5f5f5",
    accentForeground: "#0b0b0b",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2a2a2a",
    input: "#2a2a2a",
    ring: "#f5f5f5",
  },
  spacing: calNeutralTheme.spacing,
  radius: calNeutralTheme.radius,
  typography: calNeutralTheme.typography,
};
